# Generated by Django 3.0.5 on 2020-04-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height_factor', models.FloatField(default=1.0)),
                ('width_factor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('text', models.TextField(max_length=10000)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tool.Document')),
            ],
        ),
        migrations.CreateModel(
            name='TextLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('text', models.TextField(max_length=1000)),
                ('category', models.ManyToManyField(to='tool.Category')),
                ('paragraph', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tool.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentLabel',
            fields=[
                ('startX', models.ImageField(upload_to='')),
                ('startY', models.IntegerField()),
                ('width', models.ImageField(upload_to='')),
                ('height', models.ImageField(upload_to='')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tool.Document')),
                ('category', models.ManyToManyField(to='tool.Category')),
            ],
        ),
    ]
