# Generated by Django 3.0.5 on 2020-05-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlabel',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='documentlabel',
            name='width',
            field=models.IntegerField(),
        ),
    ]
