# Generated by Django 3.0.6 on 2020-05-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlabel',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentlabels', to='tool.Document'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='tool.Document'),
        ),
        migrations.AlterField(
            model_name='textlabel',
            name='paragraph',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='textlabels', to='tool.Paragraph'),
        ),
    ]
