# Generated by Django 3.0.6 on 2020-05-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20200508_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textlabel',
            name='category',
        ),
        migrations.AddField(
            model_name='textlabel',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
