# Generated by Django 3.0.5 on 2020-05-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20200501_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentlabel',
            name='category',
        ),
        migrations.AddField(
            model_name='documentlabel',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
